#!/usr/bin/env bash

set -eu
set -o pipefail

: "${KUSTOMIZE_BIN:=kustomize}"
: "${KUBECTL_BIN:=kubectl}"
USE_KUBECTL=false

get_kust_bin() {
  if ! which "${KUSTOMIZE_BIN}" &>/dev/null; then
    if ! which "${KUBECTL_BIN}" &>/dev/null; then
      echo -e "\033[1;31m[ERROR]: can't find ${KUSTOMIZE_BIN} or ${KUBECTL_BIN} installed\033[0m"
      exit 1
    fi
    KUSTOMIZE_BIN="${KUBECTL_BIN}"
    USE_KUBECTL=true
  fi
}

check_deps() {
  local missed=0
  local -A deps=([yq]=https://github.com/mikefarah/yq [vals]=https://github.com/helmfile/vals)
  for dep in yq vals; do
    if ! which "${dep}" &>/dev/null; then
      echo -e "\033[1;31m[ERROR]: ${dep} is required, download from ${deps[$dep]}/releases\033[0m"
      ((missed += 1))
    fi
  done
  [ $missed -eq 0 ]
}

WORKDIR=.
SUB_COMMAND=""
BOOL_FLAG=true
SHOW_HELP=false
declare -a GLOBAL_FLAGS=() SUB_FLAGS=() KUST_FILES=() KUST_DIRS=()
CMDS="(build|cfg|completion|create|edit|fn|help|localize|version|docs-fn|docs-fn-spec|docs-io-annotations|docs-merge|docs-merge3|tutorials-command-basics|tutorials-function-basics)"

parse_flags() {
  for flag in "$@"; do
    if [ "$flag" == "-h" ] || [ "$flag" == "--help" ]; then
      SHOW_HELP=true
    fi
    if [ -z "$SUB_COMMAND" ] && [[ $flag =~ ^$CMDS$ ]]; then
      SUB_COMMAND="$flag"
    elif [ -z "$SUB_COMMAND" ] || [ "$flag" == "--stack-trace" ]; then
      GLOBAL_FLAGS+=("$flag")
    else
      SUB_FLAGS+=("$flag")
      if [ "$SUB_COMMAND" == build ]; then
        case "$flag" in
        -e | --env | --load-restrictor | --mount | --network-name | -o | --output | --helm-command)
          BOOL_FLAG=false
          ;;
        -*)
          BOOL_FLAG=true
          ;;
        *)
          if [ "$BOOL_FLAG" == true ]; then
            KUST_DIRS+=("$flag")
          fi
          BOOL_FLAG=true
          ;;
        esac
      fi
    fi
  done
  WORKDIR="${KUST_DIRS[0]:-.}"
}

revert_kust_file() {
  mv "${KUST_FILES[0]}.backup" "${KUST_FILES[0]}"
}

backup_kust_file() {
  cp "${KUST_FILES[0]}" "${KUST_FILES[0]}".backup
  trap 'revert_kust_file' EXIT
}

# the regexp for uri experission of vals
# https://github.com/helmfile/vals/blob/main/pkg/expansion/expand_match.go#L15
VALS_REF_REGEX='((secret)?ref)\+([^\+:]*:\/\/[^\+\n "]+)\+?'

check_vals_ref_uri() {
  local count=0
  for entry in files literals; do
    while read -r line; do
      if [[ "$line" =~ ^=?$VALS_REF_REGEX ]]; then
        echo -e "\033[1;31m[ERROR]: invalid $entry source: [$line], expected key=value \033[0m"
        ((count += 1))
      fi
    done < <(ENTRY="$entry" yq '.secretGenerator[][strenv(ENTRY)][]' "${KUST_FILES[0]}")
  done
  [ $count -eq 0 ]
}

update_kust_file() {
  #shellcheck disable=SC2016
  WORKDIR="$WORKDIR/" REF_REGEX="$VALS_REF_REGEX" yq -ie 'with(.secretGenerator[];
      .literals += [(.files[]|select(test(strenv(REF_REGEX))))] |
      del(.files[] | select(test(strenv(REF_REGEX)))) |
      .literals[] |= (
        select(test(".*ref\+(sops|tfstate|file)://[^/]+")) | sub("(ref\+(sops|tfstate|file)://)", "${1}" + strenv(WORKDIR))
      )
    )' "${KUST_FILES[0]}"
}

exec_kust_vals() {
  ${KUSTOMIZE_BIN} "$@" |
    yq 'select(.kind == "Secret").data[]|=(.|sub("\n", "")|@base64d)' |
    vals eval -f - |
    yq 'select(.kind == "Secret").data[]|=@base64'
}

get_kust_files() {
  for fn in kustomization.yaml kustomization.yml Kustomization; do
    if [ -e "$WORKDIR/$fn" ]; then
      KUST_FILES+=("$WORKDIR/$fn")
    fi
  done
}

build_wrapper() {
  get_kust_files
  if [ "${#KUST_FILES[@]}" -eq 1 ]; then
    check_vals_ref_uri
    backup_kust_file
    update_kust_file
    exec_kust_vals "$@"
    exit 0
  fi
}

# shellcheck disable=SC2091
if ! $(return 0 2>/dev/null); then
  get_kust_bin
  check_deps
  parse_flags "$@"
  if [ "${#KUST_DIRS[@]}" -lt 2 ] && [ "$SUB_COMMAND" == build ] && [ "$SHOW_HELP" == false ]; then
    if [ "$USE_KUBECTL" == true ]; then
      set -- kustomize "${SUB_FLAGS[@]}"
    fi
    build_wrapper "$@"
  fi
  ${KUSTOMIZE_BIN} "$@"
fi
